#See https://github.com/zricethezav/gitleaks#configuration

title = "Foundry Template"

[extend]
useDefault = true

[[rules]]
id = "ethereum-rule-1"
description = "Ethereum private keys"
regex = '''(?:\'|"|\s|^)(?:0x)?[a-fA-F0-9]{64}(?:\'|"|\s|;|$)'''


[allowlist]
paths = [
  '''lib/(.*?)''',
  '''out/(.*?)''',
  '''cache/(.*?)''',
  '''node_modules/(.*?)''',
  '''test/utils/Addresses.sol''',
  '''test/oracles/providers/TellorOracle.t.sol''',
]
