[profile.default]
name = 'contracts-template'
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.17"
evm_version = "shanghai"
fs_permissions = [{ access = "read-write", path = "./" }]

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
single_line_statement_blocks = "preserve" # can force either way
exclude = ['lib/']

[fuzz]
runs = 100
# max_test_rejects = 10000000
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
